const { Model, DataTypes } = require("sequelize");
const sequelize = require("../config/database");

class User extends Model {
  static uniqueName() {
    return "UserModel";
  }
}

User.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    username: DataTypes.STRING,
    password: DataTypes.STRING,
    name: DataTypes.STRING,
    avatar: DataTypes.STRING,
    remember_token: DataTypes.STRING,
    created_at: DataTypes.STRING,
    updated_at: DataTypes.STRING,
    enterprise_id: DataTypes.STRING,
    first_name: DataTypes.STRING,
    last_name: DataTypes.STRING,
    date_of_birth: DataTypes.STRING,
    place_of_birth: DataTypes.STRING,
    sex: DataTypes.STRING,
    home_address: DataTypes.STRING,
    current_address: DataTypes.STRING,
    phone_number_1: DataTypes.STRING,
    phone_number_2: DataTypes.STRING,
    email: DataTypes.STRING,
    nationality: DataTypes.STRING,
    religion: DataTypes.STRING,
    spouse_name: DataTypes.STRING,
    spouse_phone: DataTypes.STRING,
    father_name: DataTypes.STRING,
    father_phone: DataTypes.STRING,
    mother_name: DataTypes.STRING,
    mother_phone: DataTypes.STRING,
    languages: DataTypes.STRING,
    emergency_person_name: DataTypes.STRING,
    emergency_person_phone: DataTypes.STRING,
    national_id_number: DataTypes.STRING,
    passport_number: DataTypes.STRING,
    tin: DataTypes.STRING,
    nssf_number: DataTypes.STRING,
    bank_name: DataTypes.STRING,
    bank_account_number: DataTypes.STRING,
    primary_school_name: DataTypes.STRING,
    primary_school_year_graduated: DataTypes.STRING,
    seconday_school_name: DataTypes.STRING,
    seconday_school_year_graduated: DataTypes.STRING,
    high_school_name: DataTypes.STRING,
    high_school_year_graduated: DataTypes.STRING,
    degree_university_name: DataTypes.STRING,
    degree_university_year_graduated: DataTypes.STRING,
    masters_university_name: DataTypes.STRING,
    masters_university_year_graduated: DataTypes.STRING,
    phd_university_name: DataTypes.STRING,
    phd_university_year_graduated: DataTypes.STRING,
    user_type: DataTypes.STRING,
    demo_id: DataTypes.STRING,
    user_id: DataTypes.STRING,
    user_batch_importer_id: DataTypes.STRING,
    school_pay_account_id: DataTypes.STRING,
    school_pay_payment_code: DataTypes.STRING,
    given_name: DataTypes.STRING,
    deleted_at: DataTypes.STRING,
    marital_status: DataTypes.STRING,
    verification: DataTypes.STRING,
    current_class_id: DataTypes.STRING,
    current_theology_class_id: DataTypes.STRING,
    status: DataTypes.STRING,
    parent_id: DataTypes.STRING,
    main_role_id: DataTypes.STRING,
    stream_id: DataTypes.STRING,
    account_id: DataTypes.STRING,
    has_personal_info: DataTypes.STRING,
    has_educational_info: DataTypes.STRING,
    has_account_info: DataTypes.STRING,
    diploma_school_name: DataTypes.STRING,
    diploma_year_graduated: DataTypes.STRING,
    certificate_school_name: DataTypes.STRING,
    certificate_year_graduated: DataTypes.STRING,
    company_id: DataTypes.STRING,
    managed_by: DataTypes.STRING,
    title: DataTypes.STRING,
    dob: DataTypes.STRING,
    intro: DataTypes.STRING,
    rate: DataTypes.STRING,
    can_evaluate: DataTypes.STRING,
    work_load_pending: DataTypes.STRING,
    work_load_completed: DataTypes.STRING,
    belongs_to_company: DataTypes.STRING,
    card_status: DataTypes.STRING,
    card_number: DataTypes.STRING,
    card_balance: DataTypes.STRING,
    card_accepts_credit: DataTypes.STRING,
    card_max_credit: DataTypes.STRING,
    card_accepts_cash: DataTypes.STRING,
    is_dependent: DataTypes.STRING,
    dependent_status: DataTypes.STRING,
    dependent_id: DataTypes.STRING,
    card_expiry: DataTypes.STRING,
    belongs_to_company_statust: DataTypes.STRING,
  },
  {
    sequelize,
    modelName: "User",
    tableName: "users",
    timestamps: false,
  }
);

module.exports = User;
